# Generated by Django 2.2.5 on 2019-09-22 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorturl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlentry',
            name='short_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
